spring:
  datasource:
    hikari:
      idle-timeout: '10000'
      maximum-pool-size: '5'
      minimum-idle: '3'
    username: postgres
    url: jdbc:postgresql://localhost:5432/algafood
    password: 'y12i'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/test
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
      FAIL_ON_IGNORED_PROPERTIES: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  mail:
    host: SMTP
    port: 10
    username: USERNAME
    password: PASSWORD
  freemarker:
    settings:
      locale: pt_BR
algafood:
  storage:
    type: LOCAL
    local:
      directory: /photos
    s3:
      id-access-key: ID_ACCESS_KEY
      secret-access-key: SECRET_ACCESS_KEY
      bucket: BUCKET
      region: US_EAST_1
      directory: DIRECTORY
  email:
    sender: SENDER
    impl: FAKE
    sandbox:
      recipient: EMAIL_RECIPIENT