spring:
  datasource:
    hikari:
      idle-timeout: '10000'
      maximum-pool-size: '5'
      minimum-idle: '3'
    username: postgres
    url: jdbc:postgresql://localhost:5432/algafood
    password: '121797'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/test
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
      FAIL_ON_IGNORED_PROPERTIES: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false